language: go
go: 
 - "1.11.x"

os: osx

env:
  - CGO_CFLAGS=-I${TRAVIS_BUILD_DIR}/vst2sdk/
  - GO111MODULE=on

addons:
  ssh_known_hosts:
  - github.com
  - ssh.github.com

before_install:
  - >-
    openssl aes-256-cbc 
    -K $encrypted_87b4f940d6a2_key 
    -iv $encrypted_87b4f940d6a2_iv 
    -in vstsdk_rsa.enc 
    -out vstsdk_rsa 
    -d
  - chmod 600 vstsdk_rsa
  - eval $(ssh-agent -s)
  - ssh-add vstsdk_rsa
  - git clone ssh://git@github.com/dudk/vst2sdk.git